# Generated by Django 3.2 on 2021-06-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
